### ISSUE TITLE
change readme into readme.rst

### ISSUE THREAD

**Issue by goFrendiAsgard** [rioastamal/miras#1]
Dear, Mas astasoft,

Maaf sebelumnya :D
Kalau readme diubah menjadi readme.rst, sepertinya tampilannya akan lebih bagus.

BTW idenya unik juga, MVC tapi prosedural. 
Salam kenal,
goFrendiAsgard

**Comment by rioastamal** [comment]
Halo goFrendiAsgard,

Yang dimaksud lebih bagus itu yg mana ya? apa agar pelafalannya mirip dengan "miras" karena akhiran m.rst?

**Comment by goFrendiAsgard** [comment]
bukan, maksud saya, kalau file readme di rename menjadi readme.rst, maka tulisan  

PENGENALAN

di readme akan ditampilkan menjadi

## PENGENALAN

(berubah menjadi header).
Seperti https://github.com/goFrendiAsgard/Neo-CMS
coba lihat raw code dari readme.rst saya, sama persis dengan punya anda :D

Sebenarnya ini bukan masalah yang terlalu penting :D

BTW, Mas astasoft, kuliah di ITS? (cuma ingin tau)

**Comment by rioastamal** [comment]
oalah.. saya nggak tau kalau bisa dibegitukan hehehe :D. Mantab bro nanti saya ubah.

Sayang sekali yang bertanya adalah cowok coba kalo cewek hahaha (becanda). Saya kuliah di STIKOM, masih statusnya MABA (Mahasiswa Bangkotan). Masnya anak ITS? yang develop NEO-CMS itu anda? bagus konsepnya. Hampir mirip dengan apa yang saya buat di http://www.raweet.org/ tapi belum saya rilis (dan enggak tau kapan) soalnya lebih sering saya buat kepentingan pribadi.

**Comment by goFrendiAsgard** [comment]
iya, kuliah di ITS, MABA juga :D
klo Neo-CMS kan tinggal comot2 dari yang udah ada.
Yang saya salut itu, anda bikin sendiri dari awal,.... cool :D
